gg.jte.development-mode=true
spring.application.name=SpringBootLabb1MS
spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=jdbc:postgresql://localhost:5432/bookdb
spring.datasource.username=user
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
