CREATE TABLE book
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(200),
    author           VARCHAR(120),
    description      VARCHAR(2000),
    publisher        VARCHAR(120),
    publication_date date,
    isbn             VARCHAR(20),
    CONSTRAINT pk_book PRIMARY KEY (id)
);